# Generated by Django 5.2.11 on 2026-02-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SdsFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("md5", models.CharField(max_length=32, unique=True)),
                ("file_path", models.CharField(max_length=500)),
                ("md5_content", models.CharField(max_length=32)),
                ("content", models.TextField()),
                ("version_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
