# Generated by Django 5.2.11 on 2026-02-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extractions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sdsfile",
            name="version_date",
            field=models.DateField(),
        ),
    ]
