# Generated by Django 5.2.11 on 2026-02-24 22:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extractions", "0002_alter_sdsfile_version_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sdsfile",
            old_name="version_date",
            new_name="revision_date",
        ),
        migrations.AddField(
            model_name="sdsfile",
            name="revision_str",
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
