# Generated by Django 5.2.11 on 2026-02-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extractions", "0003_rename_version_date_sdsfile_revision_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sdsfile",
            name="content",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="sdsfile",
            name="md5_content",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="sdsfile",
            name="revision_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="sdsfile",
            name="revision_str",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
