# Generated by Django 5.2.11 on 2026-02-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "extractions",
            "0004_alter_sdsfile_content_alter_sdsfile_md5_content_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="sdsfile",
            name="md5",
            field=models.CharField(max_length=32),
        ),
    ]
