# Generated by Django 5.2.11 on 2026-02-26 17:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("extractions", "0005_alter_sdsfile_md5"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="sdsfile",
            table="sds_files",
        ),
    ]
