# Generated by Django 5.2.11 on 2026-02-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extractions", "0007_sdsfile_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="sdsfile",
            name="is_deleted",
            field=models.BooleanField(null=True),
        ),
    ]
